[package]
name = "plygui-testable"
version = "0.0.1"
authors = ["Serhii Plyhun <snuk188@gmail.com>"]
edition = "2018"

[lib]
name = "plygui_testable"
path = "src/lib.rs"

[dependencies.plygui-api]
path = "../api"
